version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/sodateyo
      - public-data:/sodateyo/public
      - tmp-data:/sodateyo/tmp
      - log-data:/sodateyo/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: nginx
    volumes:
      - public-data:/sodateyo/public
      - tmp-data:/sodateyo/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: